In [1]:
import numpy as np
import pandas as pd #data analysis

In [2]:
data=pd.read_csv("/content/fraud_transactions_synthetic.csv")

In [3]:
data.head() #head() allows us to display the first 5 records of the dataset

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score,is_fraud
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327,0
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084,0
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303,0
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368,0
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630,1

In [9]:
data.shape #here we have 40,000 rows and 11 columns
#out of 11 columns, 10 columns/features are belonging to the independent category - they are the input features to the NN
#and only 1 is a dependent column

(40000, 11)

In [4]:
import tensorflow as tf
from tensorflow import keras #one of the most important modules within Tensorflow
from tensorflow.keras import layers #layers will help us in developing the neural network layers

In [5]:
#divide the data into dependent and independent colums
x=data.drop(['is_fraud'],axis=1) #stores the independent columnns
y=data['is_fraud'] #stores the dependent or the target column

In [6]:
x.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score
0,33.006818,15,5.500706,1,0,0,1968,1,0,0.141327
1,17.491861,2,45.404859,0,0,0,883,2,1,0.249084
2,38.385836,5,1.889033,0,0,0,257,0,0,0.175303
3,92.114269,19,7.925388,0,0,0,3025,3,0,0.060368
4,15.892489,3,45.704719,0,0,0,1651,1,0,0.274630

In [7]:
y.head()

0    0
1    0
2    0
3    0
4    1
Name: is_fraud, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25)

In [31]:
x_train.shape

(30000, 10)

In [32]:
x_test.head()

,amount,hour,distance_km,failed_logins_24h,is_international,is_new_device,account_age_days,txn_velocity_1h,prev_chargebacks,merchant_risk_score
13459,19.047731,20,0.054673,0,0,0,1243,3,0,0.131669
4012,7.500779,0,7.708498,1,0,0,2280,0,0,0.115611
22656,53.578588,20,6.519632,1,0,1,3521,2,0,0.345467
35736,22.312498,15,18.135467,0,1,0,1173,0,0,0.059662
33037,95.408374,23,13.768647,0,0,0,2990,1,0,0.460712

In [34]:
x_test.shape

(10000, 10)

In [12]:
x_train.shape[1] #total of 10 neurons are required for us to create the input layer of the NN

10

In [35]:
#building the NN using Tensorflow and Keras - we build it like a Sequential Model with layers stacked on top of each other
model=keras.Sequential([
    layers.Input(shape=(x_train.shape[1],),name='input_layer'), #input_layer has 10 neurons
    layers.Dense(16,activation='relu',name='hidden_layer_1'), #hidden_layer_1 has 16 neurons
    layers.Dense(32,activation='relu',name='hidden_layer_2'), #hidden_layer_2 has 32 neurons
    layers.Dense(1,activation='softmax',name='output_layer') #output_layer has just 1 neuron since it is a binary classifier
])

In [36]:
model.compile(
    optimizer='adam', #optimizer will ensure that the gradient loss is within the range
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [37]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10

/usr/local/lib/python3.12/dist-packages/keras/src/ops/nn.py:947: UserWarning: You are using a softmax over axis -1 of a tensor of shape (None, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(

938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.0600 - loss: 0.5328
Epoch 2/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0600 - loss: 0.4115
Epoch 3/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0600 - loss: 0.3782
Epoch 4/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0600 - loss: 0.3785
Epoch 5/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0600 - loss: 0.4002
Epoch 6/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0600 - loss: 0.3029
Epoch 7/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.0600 - loss: 0.2883
Epoch 8/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0600 - loss: 0.2893
Epoch 9/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0600 - loss: 0.2751
Epoch 10/10
938/938 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.0600 - loss: 0.2685

In [20]:
y_pred=model.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [21]:
print(y_pred)

[[0.07074606]
 [0.0133348 ]
 [0.02130965]
 ...
 [0.06497267]
 [0.08808717]
 [0.04186443]]